#452 support customfield data type
picandocodigo/List-Category-Posts pull request #465
Opened 2021-08-26 13:56 UTC by vosykapavel

- customfield_orderby - You can order the posts by a custom field. For example: [catlist numberposts=-1 customfield_orderby=Mood order=desc] will list all the posts with a "Mood" custom field. This parameter can be used toghether with customfield_name and customfield_value, you can use those parameters to select posts and then customfield_orderby to sort by this or another custom field. For other than alphabetical sorting, you can use customfield_type parameter (NUMERIC, BINARY, CHAR, DATE, DATETIME, DECIMAL, SIGNED, TIME, UNSIGNED). Remember the default order is descending, more on order:

2021-08-31 21:01 UTC, klemens-st requested changes
I left one comment in the code, it's a small thing but would be good to fix it to keep the code clear.

I also think the new shortcode parameter should be `customfield_orderby_type` so that it is absolutely clear it is used for the orderby feature and not something else, would also look better in the docs. What do you think?

2021-09-01 12:09 UTC, vosykapavel commented on include/lcp-meta-query.php
> +	  }
Thanks for your review. 

### Isset / empty
Sorry. With "isset()" I got blindly inspired here, but it's in different context there: https://github.com/picandocodigo/List-Category-Posts/blob/master/include/lcp-meta-query.php#L118

### default type
So I totally removed the default 'CHAR' and put 'type' only if not empty the parameter. (if it still works anyway) 

### parameter name
And I renamed it customfield_orderby_type.

2021-09-02 07:08 UTC, klemens-st approved these changes
Thanks! Looks good 👍

2021-09-02 07:23 UTC, merged

2021-09-02 07:59 UTC, klemens-st commented
Thanks a lot for the contribution @vosykapavel 🎆 It will be included in version 0.85.